In [1]:
tup = (1, 2, 3)
tup = tup + (1,)
tup

(1, 2, 3, 1)

In [2]:
import numpy as np


In [3]:
a = np.array([1, 2, 3])

In [4]:
a.shape

(3,)

In [5]:
b = np.array([[1, 2], 
              [3, 4]])

In [6]:
b

array([[1, 2],
       [3, 4]])

In [7]:
b.ndim

2

In [8]:
b.shape

(2, 2)

In [9]:
b = np.array([[-4, 5], 
              [0,0 ]])

In [10]:
b

array([[-4,  5],
       [ 0,  0]])

In [11]:
np.linalg.det(b)

0.0

In [12]:
np.linalg.inv(b)

LinAlgError: Singular matrix

In [13]:
b = np.array([[-1, 0], [3, 0]])

In [14]:
np.linalg.det(b)

0.0

In [15]:
# np.linalg.inv(b)

In [16]:
b

array([[-1,  0],
       [ 3,  0]])

In [17]:
b

array([[-1,  0],
       [ 3,  0]])

In [18]:
b = np.array([[10, 1], [0, 5]])

In [19]:
np.linalg.det(b)

50.000000000000014

In [20]:
b

array([[10,  1],
       [ 0,  5]])

In [21]:
value, vectors = np.linalg.eig(b)

In [22]:
vectors

array([[ 1.        , -0.19611614],
       [ 0.        ,  0.98058068]])

In [23]:
value

array([10.,  5.])

In [24]:
b = np.array([[-1, 0], [3, 0]])

In [25]:
b

array([[-1,  0],
       [ 3,  0]])

In [26]:
np.linalg.det(b)

0.0

In [27]:
value, vectors = np.linalg.eig(b)

In [28]:
value

array([ 0., -1.])

In [29]:
vectors

array([[ 0.        ,  0.31622777],
       [ 1.        , -0.9486833 ]])

In [30]:
a = np.array([[[1, 2], 
               [3, 4], 
               [5, 6], 
               [7, 8]]])

In [31]:
a

array([[[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]])

In [32]:
a.ndim

3

In [33]:
a = np.array([1, 2, 3])

In [34]:
a.ndim

1

In [35]:
a.shape

(3,)

In [36]:
b

array([[-1,  0],
       [ 3,  0]])

In [37]:
b.ndim

2

In [38]:
b.shape

(2, 2)

In [39]:
c = np.array([[[1, 2], 
               [3, 4], 
               [5, 6], 
               [7, 8]]])

In [40]:
c.ndim

3

In [41]:
c.shape

(1, 4, 2)

In [42]:
b

array([[-1,  0],
       [ 3,  0]])

In [43]:
for i in np.nditer(c):
    print(i)

1
2
3
4
5
6
7
8


In [44]:
# random generation of matrix

In [45]:
np.random.random((2, 3))

array([[0.4431926 , 0.0072537 , 0.69759177],
       [0.2181046 , 0.24223955, 0.4633808 ]])

In [46]:
np.random.randint(-1, 20, (2,3))

array([[ 1, 15, 16],
       [19,  2,  0]])

In [47]:
np.random.randn(6, 2)

array([[ 1.12401421, -0.06347708],
       [ 0.88812789,  1.11302625],
       [-0.38980974, -0.15713381],
       [-0.87142856, -1.08181838],
       [-0.00324124, -0.53626363],
       [ 0.68072664,  1.06834505]])

In [48]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [49]:
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [51]:
np.ones((5, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [52]:
np.full((3, 5), 4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [53]:
rn_mat = np.eye(6)

In [54]:
rn_mat.shape

(6, 6)

In [55]:
rn_mat.ndim

2

In [56]:
rn_mat

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [57]:
rn_mat[:3, :3]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
rn_mat[[0, 1, 5], [2, 3, 1]]

array([0., 0., 0.])

In [59]:
a = np.array([[[1, 2, 4,3]]])

In [60]:
a.ndim

3

In [61]:
a.shape

(1, 1, 4)

In [62]:
# np.arange(100000, 1000000, 998)

In [63]:
np.arange(-5,10,1).ndim

1

In [64]:
a.shape

(1, 1, 4)

In [65]:
a.ndim

3

In [66]:
a = np.linspace(-10, 10, 10)

In [67]:
a

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [68]:
a*2

array([-20.        , -15.55555556, -11.11111111,  -6.66666667,
        -2.22222222,   2.22222222,   6.66666667,  11.11111111,
        15.55555556,  20.        ])

In [69]:
a + 2

array([-8.        , -5.77777778, -3.55555556, -1.33333333,  0.88888889,
        3.11111111,  5.33333333,  7.55555556,  9.77777778, 12.        ])

In [70]:
a = np.eye(4)

In [71]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [72]:
np.hsplit(a, 2)

[array([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [1., 0.],
        [0., 1.]])]

In [73]:
np.vsplit(a, 2)

[array([[1., 0., 0., 0.],
        [0., 1., 0., 0.]]),
 array([[0., 0., 1., 0.],
        [0., 0., 0., 1.]])]

In [74]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [75]:
b = np.full((4, 4), 4)

In [76]:
b

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

In [77]:
a.dot(b)

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [78]:
a = np.array([1, 2])
b = np.array([3, 4])

In [79]:
np.dot(a, b)

11

In [80]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

In [81]:
a + b

array([[ 6,  8],
       [10, 12]])

In [82]:
a - b

array([[-4, -4],
       [-4, -4]])

In [83]:
a * b

array([[ 5, 12],
       [21, 32]])

In [84]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [85]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [86]:
a = np.random.random((5, 9))

In [87]:
a

array([[0.69683062, 0.28077188, 0.00895735, 0.39082995, 0.20541367,
        0.45835431, 0.78000579, 0.6721214 , 0.14445746],
       [0.62960381, 0.93831787, 0.19208364, 0.14123652, 0.05074039,
        0.6279318 , 0.88472679, 0.99579528, 0.93535985],
       [0.55280924, 0.09888649, 0.43523694, 0.63217594, 0.89485138,
        0.48200802, 0.27232539, 0.09620844, 0.59480986],
       [0.31979979, 0.5520186 , 0.57295049, 0.94684861, 0.93341884,
        0.37249869, 0.68117007, 0.98013883, 0.61235392],
       [0.3606948 , 0.68065868, 0.19236859, 0.47646197, 0.09322089,
        0.5349183 , 0.45782762, 0.26075314, 0.21749953]])

In [88]:
a.T

array([[0.69683062, 0.62960381, 0.55280924, 0.31979979, 0.3606948 ],
       [0.28077188, 0.93831787, 0.09888649, 0.5520186 , 0.68065868],
       [0.00895735, 0.19208364, 0.43523694, 0.57295049, 0.19236859],
       [0.39082995, 0.14123652, 0.63217594, 0.94684861, 0.47646197],
       [0.20541367, 0.05074039, 0.89485138, 0.93341884, 0.09322089],
       [0.45835431, 0.6279318 , 0.48200802, 0.37249869, 0.5349183 ],
       [0.78000579, 0.88472679, 0.27232539, 0.68117007, 0.45782762],
       [0.6721214 , 0.99579528, 0.09620844, 0.98013883, 0.26075314],
       [0.14445746, 0.93535985, 0.59480986, 0.61235392, 0.21749953]])

In [89]:
a = np.random.random((3, 4))

In [90]:
a

array([[0.63709785, 0.06682912, 0.74962404, 0.12889946],
       [0.70486181, 0.56322681, 0.8306281 , 0.68583697],
       [0.20752082, 0.15969526, 0.9573395 , 0.15761738]])

In [91]:
a.T

array([[0.63709785, 0.70486181, 0.20752082],
       [0.06682912, 0.56322681, 0.15969526],
       [0.74962404, 0.8306281 , 0.9573395 ],
       [0.12889946, 0.68583697, 0.15761738]])

In [92]:
a.reshape((4, 3))

array([[0.63709785, 0.06682912, 0.74962404],
       [0.12889946, 0.70486181, 0.56322681],
       [0.8306281 , 0.68583697, 0.20752082],
       [0.15969526, 0.9573395 , 0.15761738]])

In [93]:
a.ravel()

array([0.63709785, 0.06682912, 0.74962404, 0.12889946, 0.70486181,
       0.56322681, 0.8306281 , 0.68583697, 0.20752082, 0.15969526,
       0.9573395 , 0.15761738])

In [94]:
a = np.array([[[1, 2, 3, 4] ,[1, 2, 2, 3]]])

In [95]:
a

array([[[1, 2, 3, 4],
        [1, 2, 2, 3]]])

In [96]:
a.ndim

3

In [97]:
a.shape

(1, 2, 4)

In [98]:
a.ravel().shape

(8,)

In [99]:
a


array([[[1, 2, 3, 4],
        [1, 2, 2, 3]]])

In [100]:
b

array([[5, 6],
       [7, 8]])

In [101]:
a = np.array([[1, 2, 3, 4], 
              [6, 7, 8, 9]])

In [102]:
np.sum(a)

40

In [103]:
sum_ = 0
for i in np.nditer(a):
    sum_ = sum_ + i

In [104]:
sum_

40

In [105]:
np.sum(a, axis = 0) # row wise

array([ 7,  9, 11, 13])

In [106]:
np.sum(a, axis = 1) # col wise

array([10, 30])

In [107]:
b

array([[5, 6],
       [7, 8]])

In [108]:
np.sum(b, axis = 0)

array([12, 14])

In [109]:
np.sum(b, axis = 1)

array([11, 15])

In [110]:
a

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [111]:
40/8

5.0

In [112]:
np.mean(a)

5.0

In [113]:
np.median(a)

5.0

In [114]:
np.var(a)

7.5

In [115]:
(np.std(a))**2

7.5

In [116]:
np.var(a)

7.5

In [117]:
a = np.array([[1, 2], [3, 4]])

In [118]:
b

array([[5, 6],
       [7, 8]])

In [119]:
c = np.stack((a, b), axis=1)

In [120]:
c

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [121]:
c.shape

(2, 2, 2)

In [122]:
a

array([[1, 2],
       [3, 4]])

In [123]:
np.insert(a, 1, 0, axis = 0)

array([[1, 2],
       [0, 0],
       [3, 4]])

In [124]:
np.sin(60)

-0.3048106211022167

In [125]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [126]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [127]:
np.log(a)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [128]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [129]:
a

array([[1, 2],
       [3, 4]])

In [132]:
a.T

array([[1, 3],
       [2, 4]])

In [133]:
a = np.random.random((4, 6))

In [136]:
a.T.shape

(6, 4)

In [137]:
a.reshape((4, 6))

array([[0.13889496, 0.55484552, 0.8438424 , 0.8166527 , 0.60308288,
        0.12164527],
       [0.83858566, 0.04533319, 0.23106846, 0.21656309, 0.50571417,
        0.17316372],
       [0.20107563, 0.46005237, 0.74497376, 0.59818352, 0.0399895 ,
        0.38204767],
       [0.730621  , 0.94571215, 0.34278433, 0.32058079, 0.7807134 ,
        0.2998754 ]])

In [147]:
a

array([[0.13889496, 0.55484552, 0.8438424 , 0.8166527 , 0.60308288,
        0.12164527],
       [0.83858566, 0.04533319, 0.23106846, 0.21656309, 0.50571417,
        0.17316372],
       [0.20107563, 0.46005237, 0.74497376, 0.59818352, 0.0399895 ,
        0.38204767],
       [0.730621  , 0.94571215, 0.34278433, 0.32058079, 0.7807134 ,
        0.2998754 ]])

In [148]:
a.reshape((8, 3))

array([[0.13889496, 0.55484552, 0.8438424 ],
       [0.8166527 , 0.60308288, 0.12164527],
       [0.83858566, 0.04533319, 0.23106846],
       [0.21656309, 0.50571417, 0.17316372],
       [0.20107563, 0.46005237, 0.74497376],
       [0.59818352, 0.0399895 , 0.38204767],
       [0.730621  , 0.94571215, 0.34278433],
       [0.32058079, 0.7807134 , 0.2998754 ]])

In [140]:
# 24 = (1, 24 ), (2, 12), (3, 8), (4, 6)

In [150]:
a.ravel().shape

(24,)