### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [12]:
l = list()

In [14]:
l = []

In [15]:
import numpy as np
a = np.array([1, 
              2, 
              3])

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.


In [16]:
a.ndim

1

In [17]:
a.shape

(3,)

In [18]:
l = [1, 2, 3, 4]

In [19]:
type(l)

list

In [20]:
l = np.array(l)
type(l)

numpy.ndarray

In [27]:
a = np.array([[[1, 2], 
              [3, 4]]])

In [28]:
a.ndim

3

In [29]:
a.shape

(1, 2, 2)

In [94]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])

In [31]:
a + b, a - b, a*b, a/b

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [32]:
a%b

array([[1, 2],
       [3, 4]])

In [33]:
a//b

array([[0, 0],
       [0, 0]])

In [34]:
np.add(a, b)

array([[ 6,  8],
       [10, 12]])

In [35]:
np.subtract(a, b) == np.subtract(b, a)

array([[False, False],
       [False, False]])

In [37]:
np.multiply(a, b), np.divide(a, b)

(array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [38]:
a

array([[1, 2],
       [3, 4]])

In [39]:
np.sum(a)

10

In [43]:
np.sum(a, axis  = 1)

array([3, 7])

In [44]:
np.sum(b, axis = 0)

array([12, 14])

In [45]:
b

array([[5, 6],
       [7, 8]])

In [48]:
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [52]:
np.ones((2, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [55]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [61]:
np.full((2, 5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [62]:
l

array([1, 2, 3, 4])

In [63]:
l = list(l)

In [64]:
for i in l:
    print(i)

1
2
3
4


In [65]:
a

array([[1, 2],
       [3, 4]])

In [66]:
l = list(a)

In [67]:
l

[array([1, 2]), array([3, 4])]

In [68]:
l = [1, 2, 3, 4]

In [69]:
a

array([[1, 2],
       [3, 4]])

In [72]:
for i in list(a.ravel()):
    print(i)

1
2
3
4


In [74]:
for i in np.nditer(a):
    print(i)

1
2
3
4


In [75]:
a = np.random.random((2, 3))

In [76]:
a

array([[0.48388372, 0.59699717, 0.19954541],
       [0.24644031, 0.04476648, 0.34631015]])

In [85]:
a = np.random.randint(0, 10, (5, 2))

In [86]:
a

array([[1, 5],
       [1, 4],
       [4, 8],
       [8, 7],
       [1, 4]])

In [90]:
a = np.random.randn(3, 2)

In [91]:
a

array([[ 0.19216175, -0.84820318],
       [-0.32132511,  0.06684725],
       [ 0.81073128,  0.14612812]])

In [92]:
np.random.rand(2, 3)

array([[0.94212069, 0.33650449, 0.33344045],
       [0.48858656, 0.70543592, 0.68283767]])

In [93]:
a

array([[ 0.19216175, -0.84820318],
       [-0.32132511,  0.06684725],
       [ 0.81073128,  0.14612812]])

In [95]:
a

array([[1, 2],
       [3, 4]])

In [96]:
b

array([[5, 6],
       [7, 8]])

In [97]:
a*b

array([[ 5, 12],
       [21, 32]])

In [99]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [100]:
np.dot(a, b) == np.dot(b, a)

array([[False, False],
       [False, False]])

In [101]:
a@b

array([[19, 22],
       [43, 50]])

In [102]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [103]:
rn_mat = np.random.randint(0, 10, (4, 5))

In [104]:
rn_mat

array([[0, 5, 4, 6, 5],
       [3, 8, 1, 6, 1],
       [9, 1, 9, 1, 6],
       [5, 3, 0, 3, 4]])

In [105]:
rn_mat[0]

array([0, 5, 4, 6, 5])

In [107]:
rn_mat[ : , :3 ]

array([[0, 5, 4],
       [3, 8, 1],
       [9, 1, 9],
       [5, 3, 0]])

In [109]:
rn_mat[2:, 3:]

array([[1, 6],
       [3, 4]])

In [112]:
rn_mat[[0, 3],3 :]

array([[6, 5],
       [3, 4]])

In [114]:
np.median(a)

2.5

In [116]:
np.std(a)

1.118033988749895

In [117]:
np.var(a)

1.25