### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [1]:
l = list()

In [2]:
l = []

In [3]:
import numpy as np
a = np.array([1, 
              2, 
              3])

In [4]:
a.ndim

1

In [5]:
a.shape

(3,)

In [6]:
l = [1, 2, 3, 4]

In [7]:
type(l)

list

In [8]:
l = np.array(l)
type(l)

numpy.ndarray

In [9]:
a = np.array([[[1, 2], 
              [3, 4]]])

In [10]:
a.ndim

3

In [11]:
a.shape

(1, 2, 2)

In [12]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])

In [13]:
a + b, a - b, a*b, a/b

(array([[ 6,  8],
        [10, 12]]),
 array([[-4, -4],
        [-4, -4]]),
 array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [14]:
a%b

array([[1, 2],
       [3, 4]])

In [15]:
a//b

array([[0, 0],
       [0, 0]])

In [16]:
np.add(a, b)

array([[ 6,  8],
       [10, 12]])

In [17]:
np.subtract(a, b) == np.subtract(b, a)

array([[False, False],
       [False, False]])

In [18]:
np.multiply(a, b), np.divide(a, b)

(array([[ 5, 12],
        [21, 32]]),
 array([[0.2       , 0.33333333],
        [0.42857143, 0.5       ]]))

In [19]:
a

array([[1, 2],
       [3, 4]])

In [20]:
np.sum(a)

10

In [21]:
np.sum(a, axis  = 1)

array([3, 7])

In [22]:
np.sum(b, axis = 0)

array([12, 14])

In [23]:
b

array([[5, 6],
       [7, 8]])

In [24]:
np.zeros((2, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [25]:
np.ones((2, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [26]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.full((2, 5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [28]:
l

array([1, 2, 3, 4])

In [29]:
l = list(l)

In [30]:
for i in l:
    print(i)

1
2
3
4


In [31]:
a

array([[1, 2],
       [3, 4]])

In [32]:
l = list(a)

In [33]:
l

[array([1, 2]), array([3, 4])]

In [34]:
l = [1, 2, 3, 4]

In [35]:
a

array([[1, 2],
       [3, 4]])

In [36]:
for i in list(a.ravel()):
    print(i)

1
2
3
4


In [37]:
for i in np.nditer(a):
    print(i)

1
2
3
4


In [38]:
a = np.random.random((2, 3))

In [39]:
a

array([[0.06886416, 0.43771067, 0.71536328],
       [0.47297302, 0.82439127, 0.29024604]])

In [40]:
a = np.random.randint(0, 10, (5, 2))

In [41]:
a

array([[5, 5],
       [4, 2],
       [4, 9],
       [8, 4],
       [9, 7]])

In [42]:
a = np.random.randn(3, 2)

In [43]:
a

array([[ 0.58950716, -0.70142775],
       [-0.30993731,  0.29084345],
       [-0.40985065,  0.09983839]])

In [44]:
np.random.rand(2, 3)

array([[0.48187787, 0.81545049, 0.89655998],
       [0.49823177, 0.46213279, 0.93419461]])

In [45]:
a

array([[ 0.58950716, -0.70142775],
       [-0.30993731,  0.29084345],
       [-0.40985065,  0.09983839]])

In [46]:
a

array([[ 0.58950716, -0.70142775],
       [-0.30993731,  0.29084345],
       [-0.40985065,  0.09983839]])

In [47]:
b

array([[5, 6],
       [7, 8]])

In [48]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [49]:
a.dot(b)

array([[-1.96245843, -2.07437902],
       [ 0.48621757,  0.4671237 ],
       [-1.35038457, -1.66039684]])

In [50]:
np.dot(a, b) == np.dot(b, a)

ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [51]:
a@b

array([[-1.96245843, -2.07437902],
       [ 0.48621757,  0.4671237 ],
       [-1.35038457, -1.66039684]])

In [52]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [53]:
rn_mat = np.random.randint(0, 10, (4, 5))

In [54]:
rn_mat

array([[2, 6, 5, 5, 4],
       [3, 7, 0, 6, 9],
       [2, 8, 3, 1, 4],
       [0, 1, 3, 0, 0]])

In [55]:
rn_mat[0]

array([2, 6, 5, 5, 4])

In [56]:
rn_mat[ : , :3 ]

array([[2, 6, 5],
       [3, 7, 0],
       [2, 8, 3],
       [0, 1, 3]])

In [57]:
rn_mat[2:, 3:]

array([[1, 4],
       [0, 0]])

In [58]:
rn_mat[[0, 3],3 :]

array([[5, 4],
       [0, 0]])

In [59]:
np.median(a)

-0.10504946270612237

In [60]:
np.std(a)

0.44077553899364574

In [61]:
np.var(a)

0.19428307577513892

In [62]:
# y = 1/(1 + e**(-x))

In [63]:
e = 2.71
x = 0
1/(1 + e**(-0))

0.5

In [64]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [65]:
print(sigmoid(x = 0))

0.5


In [66]:
x = 1

In [67]:
np.sin(x)

0.8414709848078965

In [68]:
a = np.random.random((5, 4))

In [69]:
a.ndim,a.shape

(2, (5, 4))

In [70]:
a.transpose()

array([[0.84848894, 0.17848732, 0.51384256, 0.902949  , 0.97074203],
       [0.94905042, 0.80642752, 0.8258064 , 0.1372117 , 0.48118811],
       [0.84849067, 0.11137061, 0.99838429, 0.41858631, 0.82077619],
       [0.13629062, 0.5853448 , 0.75201562, 0.8867089 , 0.59253739]])

In [71]:
a

array([[0.84848894, 0.94905042, 0.84849067, 0.13629062],
       [0.17848732, 0.80642752, 0.11137061, 0.5853448 ],
       [0.51384256, 0.8258064 , 0.99838429, 0.75201562],
       [0.902949  , 0.1372117 , 0.41858631, 0.8867089 ],
       [0.97074203, 0.48118811, 0.82077619, 0.59253739]])

In [72]:
a.reshape(1, 20)

array([[0.84848894, 0.94905042, 0.84849067, 0.13629062, 0.17848732,
        0.80642752, 0.11137061, 0.5853448 , 0.51384256, 0.8258064 ,
        0.99838429, 0.75201562, 0.902949  , 0.1372117 , 0.41858631,
        0.8867089 , 0.97074203, 0.48118811, 0.82077619, 0.59253739]])

In [73]:
x = np.random.random((25, 25))

In [74]:
x.reshape(-1, 625).shape

(1, 625)

In [75]:
x.shape

(25, 25)

In [76]:
x.ravel().shape

(625,)

In [77]:
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6], 
              [7, 8]])

In [78]:
np.stack((a, b), axis = 0)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [79]:
np.stack((a, b), axis = 1)

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [80]:
c = np.random.randint(0, 10, (4,6))
# find the max and min values along rows and columns respectively

In [81]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [82]:
np.mean(c)

4.708333333333333

In [83]:
np.mean(c , axis = 0)

array([4.  , 5.25, 2.  , 5.75, 4.75, 6.5 ])

In [84]:
np.mean(c, axis = 1)

array([5.        , 3.66666667, 5.16666667, 5.        ])

In [85]:
a

array([[1, 2],
       [3, 4]])

In [86]:
b

array([[5, 6],
       [7, 8]])

In [87]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [90]:
e = 2.71
x = 0
f = 1/(1 + e**(-x))

In [91]:
f

0.5

In [92]:
def sigmoid(x):
    return 1/(1 + e**-x)

In [93]:
print(sigmoid(x = 1))

0.7304582210242588


In [94]:
x = 0
1/(1 + np.exp(-x))

0.5

In [96]:
c.shape


(4, 6)

In [97]:
c.ndim

2

In [95]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [102]:
c.transpose().reshape(3, 8)

array([[4, 3, 6, 3, 5, 3, 4, 9],
       [4, 0, 2, 2, 6, 1, 9, 7],
       [6, 7, 1, 5, 5, 8, 9, 4]])

In [101]:
c.reshape(8, 3)

array([[4, 5, 4],
       [6, 6, 5],
       [3, 3, 0],
       [1, 7, 8],
       [6, 4, 2],
       [9, 1, 9],
       [3, 9, 2],
       [7, 5, 4]])

In [103]:
c.reshape(-1, 4)

array([[4, 5, 4, 6],
       [6, 5, 3, 3],
       [0, 1, 7, 8],
       [6, 4, 2, 9],
       [1, 9, 3, 9],
       [2, 7, 5, 4]])

In [104]:
c.reshape(2, -1)

array([[4, 5, 4, 6, 6, 5, 3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9, 3, 9, 2, 7, 5, 4]])

In [106]:
c.reshape(-1, 8)

array([[4, 5, 4, 6, 6, 5, 3, 3],
       [0, 1, 7, 8, 6, 4, 2, 9],
       [1, 9, 3, 9, 2, 7, 5, 4]])

In [107]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [108]:
c.ravel()

array([4, 5, 4, 6, 6, 5, 3, 3, 0, 1, 7, 8, 6, 4, 2, 9, 1, 9, 3, 9, 2, 7,
       5, 4])

In [109]:
np.mean(c)

4.708333333333333

In [110]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [111]:
np.mean(c, axis = 0)

array([4.  , 5.25, 2.  , 5.75, 4.75, 6.5 ])

In [112]:
np.mean(c, axis = 1)

array([5.        , 3.66666667, 5.16666667, 5.        ])

In [113]:
np.median(c)

4.5

In [114]:
np.median(c, axis = 0)

array([3.5, 4.5, 2. , 6.5, 5.5, 6.5])

In [117]:
np.std(c)**2

6.539930555555555

In [116]:
np.var(c)

6.5399305555555545

In [118]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [119]:
# find all the numbers greater than 5

In [123]:
c[c>5]

array([6, 6, 7, 8, 6, 9, 9, 9, 7])

In [128]:
np.sort(c, axis = 0)[::-1]

array([[6, 9, 4, 9, 7, 9],
       [4, 5, 2, 7, 6, 8],
       [3, 4, 2, 6, 5, 5],
       [3, 3, 0, 1, 1, 4]])

In [129]:
b

array([[5, 6],
       [7, 8]])

In [131]:
b = np.append(b, 20)

In [132]:
b = np.append(b, 10)

In [133]:
b

array([ 5,  6,  7,  8, 20, 10])

In [137]:
b = b.reshape(2, 3)

In [138]:
b

array([[ 5,  6,  7],
       [ 8, 20, 10]])

In [136]:
a

array([[1, 2],
       [3, 4]])

In [139]:
a

array([[1, 2],
       [3, 4]])

In [140]:
b

array([[ 5,  6,  7],
       [ 8, 20, 10]])

In [144]:
# np.concatenate(a, b)

In [148]:
b = np.array([[5, 6], [7, 8]])


In [149]:
a

array([[1, 2],
       [3, 4]])

In [150]:
b

array([[5, 6],
       [7, 8]])

In [152]:
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [153]:
b

array([[5, 6],
       [7, 8]])

In [154]:
np.unique(b)

array([5, 6, 7, 8])

In [155]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [156]:
np.unique(c)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [157]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [163]:
for numbers in np.nditer(c):
    print(numbers)

4
5
4
6
6
5
3
3
0
1
7
8
6
4
2
9
1
9
3
9
2
7
5
4


In [164]:
c

array([[4, 5, 4, 6, 6, 5],
       [3, 3, 0, 1, 7, 8],
       [6, 4, 2, 9, 1, 9],
       [3, 9, 2, 7, 5, 4]])

In [165]:
np.where(c>5)

(array([0, 0, 1, 1, 2, 2, 2, 3, 3], dtype=int64),
 array([3, 4, 4, 5, 0, 3, 5, 1, 3], dtype=int64))

In [167]:
np.where(b>3)

(array([0, 0, 1, 1], dtype=int64), array([0, 1, 0, 1], dtype=int64))

In [168]:
np.argmax(b)

3

In [169]:
a

array([[1, 2],
       [3, 4]])

In [174]:
a = np.random.randint(0, 10, 10)
a

array([4, 5, 1, 3, 9, 0, 0, 7, 6, 8])

In [177]:
idx = np.argmax(a)

In [178]:
maximum = a[idx]

In [179]:
maximum

9