### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
# !pip install numpy

In [3]:
import numpy as np

In [4]:
np

<module 'numpy' from 'C:\\Users\\tbaka\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [5]:
a = np.array([1, 2, 3, 4])

In [6]:
a

array([1, 2, 3, 4])

In [9]:
b = np.array([[1, 2], 
              [3, 4]])

In [10]:
b

array([[1, 2],
       [3, 4]])

In [18]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [21]:
c # tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [24]:
a.ndim

1

In [25]:
b.ndim

2

In [26]:
c.ndim

3

In [27]:
a.shape

(4,)

In [31]:
x = np.array([[1, 
             2], 
             [3, 
             4, 
             ]])

In [32]:
x

array([[1, 2],
       [3, 4]])

In [33]:
b.shape

(2, 2)

In [35]:
b

array([[1, 2],
       [3, 4]])

In [36]:
b.ndim

2

In [37]:
b.shape

(2, 2)

In [39]:
c.ndim

3

In [40]:
c.shape

(2, 2, 2)

In [41]:
a.dtype

dtype('int32')

In [43]:
a = np.array([1, 2, 3, 4], dtype = float)

In [44]:
a

array([1., 2., 3., 4.])

In [45]:
a.dtype

dtype('float64')

In [46]:
# creating an array

In [55]:
x = np.arange(-1, 10, 1)

In [56]:
x.ndim

1

In [57]:
x.shape

(11,)

In [71]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [73]:
np.linspace(-1, 10, 7)

array([-1.        ,  0.83333333,  2.66666667,  4.5       ,  6.33333333,
        8.16666667, 10.        ])

In [74]:
np.arange(-1, 10, 7)

array([-1,  6])

In [79]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [80]:
a = np.array([[1, 2], 
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

In [84]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [85]:
a**3

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [86]:
a == b

array([[False, False],
       [False, False]])

In [141]:
rn_mat = np.random.random((5, 7))

In [142]:
rn_mat.ndim

2

In [143]:
rn_mat.shape

(5, 7)

In [144]:
rn_mat = rn_mat*100

In [145]:
rn_mat = np.round(rn_mat)

In [146]:
rn_mat

array([[15., 36., 36., 55., 48., 37., 85.],
       [ 8., 94., 58., 42., 98., 63.,  1.],
       [60., 39., 14.,  5., 62., 12., 61.],
       [ 5.,  5.,  5., 95., 63., 61., 59.],
       [ 4., 29., 60., 45., 64., 96., 14.]])

In [147]:
# axis = 1 -> row wise operations else 0 -> col wise operations
np.max(rn_mat, axis = 1)

array([85., 98., 62., 95., 96.])

In [148]:
np.max(rn_mat, axis = 0)

array([60., 94., 60., 95., 98., 96., 85.])

In [149]:
np.prod(rn_mat, axis = 1)


array([1.61406432e+11, 1.13099777e+10, 7.43389920e+09, 2.69250188e+09,
       2.69402112e+10])

In [150]:
np.prod(rn_mat, axis = 0)


array([1.44000000e+05, 1.91365200e+07, 8.76960000e+06, 4.93762500e+07,
       1.17592474e+09, 1.63804032e+08, 4.28281000e+06])

In [151]:
np.sum(a)

10

In [152]:
a

array([[1, 2],
       [3, 4]])

In [153]:
np.sum(a, axis = 0)

array([4, 6])

In [154]:
a

array([[1, 2],
       [3, 4]])

In [155]:
b

array([[5, 6],
       [7, 8]])

In [156]:
np.matmul(a, b)

array([[19, 22],
       [43, 50]])

In [157]:
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [158]:
np.dot(b, a)

array([[23, 34],
       [31, 46]])

In [159]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [160]:
b.dot(a)

array([[23, 34],
       [31, 46]])

In [161]:
a@b

array([[19, 22],
       [43, 50]])

In [162]:
rn_mat[2]

array([60., 39., 14.,  5., 62., 12., 61.])

In [163]:
rn_mat[0, 0]

15.0

In [164]:
rn_mat[0, 2]

36.0

In [165]:
rn_mat[1,3 ]

42.0

In [166]:
rn_mat[0]

array([15., 36., 36., 55., 48., 37., 85.])

In [167]:
rn_mat[ 1 :  , 2 :]

array([[58., 42., 98., 63.,  1.],
       [14.,  5., 62., 12., 61.],
       [ 5., 95., 63., 61., 59.],
       [60., 45., 64., 96., 14.]])

In [168]:
rn_mat

array([[15., 36., 36., 55., 48., 37., 85.],
       [ 8., 94., 58., 42., 98., 63.,  1.],
       [60., 39., 14.,  5., 62., 12., 61.],
       [ 5.,  5.,  5., 95., 63., 61., 59.],
       [ 4., 29., 60., 45., 64., 96., 14.]])

In [169]:
rn_mat[0]

array([15., 36., 36., 55., 48., 37., 85.])

In [171]:
rn_mat.shape

(5, 7)

In [179]:
rn_mat[ 3:, 1: 5 ]

array([[ 5.,  5., 95., 63.],
       [29., 60., 45., 64.]])

In [173]:
rn_mat

array([[15., 36., 36., 55., 48., 37., 85.],
       [ 8., 94., 58., 42., 98., 63.,  1.],
       [60., 39., 14.,  5., 62., 12., 61.],
       [ 5.,  5.,  5., 95., 63., 61., 59.],
       [ 4., 29., 60., 45., 64., 96., 14.]])