In [1]:
import numpy as np

In [36]:
a = np.array([[1, 2]])

In [33]:
a

array([[[1, 2]]])

In [25]:
a[0], a[1]

(1, 2)

In [34]:
a

array([[[1, 2]]])

In [37]:
a.ndim

2

In [38]:
a.shape

(1, 2)

In [39]:
a = np.array([1, 2])

In [40]:
a.ndim

1

In [41]:
a.shape

(2,)

In [42]:
tup = (1, 2, 3)

In [43]:
tup = tup + (1,)

In [44]:
tup

(1, 2, 3, 1)

In [47]:
v1 = np.array([2, 4])
v2 = np.array([1, 2])

In [48]:
np.linalg.norm(v)

5.0

In [50]:
np.linalg.norm(v2)

2.23606797749979

In [51]:
v1-v2

array([1, 2])

In [54]:
np.round(np.linalg.norm(v1-v2)**2)

5.0